name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Webpage
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc python3-pandocfilters make
        pandoc --version
        make page
    - name: Deploy
      if: github.repository == 'weiznich/diesel.rs-website' && github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: out # The folder the action should deploy.
        clean: true
        clean-exclude: |
          CNAME
